version: '3.4'


services:
  db:
    image: postgres:13-alpine
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  gitassessment.api:
    image: ${DOCKER_REGISTRY-}gitassessmentapi
    build:
      context: .
      dockerfile: GitAssessment.Api/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    depends_on:
      - db

volumes:
  pg_data: null